In [ ]:
#크기가 10인 null 벡터를 만드세요. (힌트: np.zeros())
#numpy 버전과 설정을 출력하세요. (힌트: np.__version__, np.show_config())
#값이 10에서 49까지인 벡터를 만드세요. (힌트: np.arange(10, 50))
#벡터를 역순으로 만드세요 (첫 번째 요소가 마지막이 됩니다). (힌트: 배열을 뒤집기 위해 [::-1])
#크기가 3x3이고 0에서 8까지의 값을 갖는 행렬을 만드세요. (힌트: np.arange()와 reshape())

In [2]:
import numpy as np

In [4]:
arr1=np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.__version__
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-8d7bajfv/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-8d7bajfv/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.29  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: C:/a/numpy/numpy/.openblas
    version: 0.3.29
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-8d7bajfv/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-8d7bajfv/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.29  US

In [12]:
arr2=np.arange(10, 50)
print(arr2)
#벡터를 역순으로 만드세요 (첫 번째 요소가 마지막이 됩니다). (힌트: 배열을 뒤집기 위해 [::-1])


print(arr2[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [33]:
arr3=np.arange(0,9).reshape(3,3)
print(arr3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#1D 배열을 3x3 행렬로 변환하세요. (힌트: reshape())
#0에서 1 사이의 랜덤한 값으로 채워진 3x3 배열을 만드세요. (힌트: np.random.random())
#5x5 단위 행렬을 만드세요. (힌트: np.eye(5))
#임의의 1D 배열에서 가장 큰 값의 인덱스를 찾으세요. (힌트: np.argmax())
#크기가 10인 배열을 생성하고, 3에서 8까지의 값을 0으로 바꾸세요. (힌트: 슬라이싱과 배열 인덱싱)

In [37]:
arr3=np.arange(0,9).reshape(3,3)
print(arr3)
print('\n')
random_array = np.random.random((3, 3))
print(random_array)
print('\n')
arr4=np.eye(5)
print(arr4)
print('\n')
print(arr2)
a = np.argmax(arr2)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[0.44680242 0.49472905 0.77363702]
 [0.8797126  0.98812596 0.96609654]
 [0.22997543 0.28224832 0.17220748]]


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
39


In [34]:
arr5=np.arange(0,11)
print(arr5)
arr5[3:9]=0
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  0  0  0  0  0  0  9 10]


In [55]:
#임의의 배열에서 가장 작은 값과 가장 큰 값을 교환하세요. (힌트: np.min(), np.max()와 인덱싱)
#3차원 배열의 각 슬라이스마다 평균값을 계산하세요. (힌트: np.mean()과 축 설정)
#크기가 100인 배열을 생성하고 평균, 표준편차를 계산하세요. (힌트: np.mean(), np.std())
#주어진 2D 배열에서 고유한 행을 찾으세요. (힌트: np.unique()와 axis 설정)
#임의의 10x10 배열에서 가장 큰 값 5개를 찾으세요. (힌트: np.argsort()와 슬라이싱)
arr5=np.arange(0,11)
a=np.argmax(arr5)
b=np.argmin(arr5)
c=np.max(arr5)
d=np.min(arr5)

arr5[b]=c
arr5[a]=d
print(arr5)


[10  1  2  3  4  5  6  7  8  9  0]


In [ ]:
arr6=np.arange(64).reshape(4,4,4)

print(np.mean(arr6[0,:6,:6]))
print(np.mean(arr6[1,:6,:6]))
print(np.mean(arr6[3,:6,:6]))


7.5
23.5
55.5


In [65]:
arr6=np.arange(100)
print(np.mean(arr6))
print(np.std(arr6))

49.5
28.86607004772212


In [ ]:
#주어진 2D 배열에서 고유한 행을 찾으세요. (힌트: np.unique()와 axis 설정)
array1 = np.tile(np.arange(1, 7).reshape(2,3), (2, 1))
array1

unique_rows = np.unique(array1, axis=0) 
print(unique_rows)

#임의의 10x10 배열에서 가장 큰 값 5개를 찾으세요. (힌트: np.argsort()와 슬라이싱)
array2 = np.arange(1,101).reshape(10,10)
print(array2)
top5 = np.sort(array2.ravel())[-5:]
print('\n')
print(top5)








[[1 2 3]
 [4 5 6]]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


[ 96  97  98  99 100]
