In [690]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

test_df = pd.read_csv('./test.csv')
test_df

datetime  season  holiday  workingday  weather   temp  \
0     2011-01-20 00:00:00       1        0           1        1  10.66   
1     2011-01-20 01:00:00       1        0           1        1  10.66   
2     2011-01-20 02:00:00       1        0           1        1  10.66   
3     2011-01-20 03:00:00       1        0           1        1  10.66   
4     2011-01-20 04:00:00       1        0           1        1  10.66   
...                   ...     ...      ...         ...      ...    ...   
6488  2012-12-31 19:00:00       1        0           1        2  10.66   
6489  2012-12-31 20:00:00       1        0           1        2  10.66   
6490  2012-12-31 21:00:00       1        0           1        1  10.66   
6491  2012-12-31 22:00:00       1        0           1        1  10.66   
6492  2012-12-31 23:00:00       1        0           1        1  10.66   

       atemp  humidity  windspeed  
0     11.365        56    26.0027  
1     13.635        56     0.0000  
2     13.635        56     0.0000  
3     12.880        56    11.0014  
4     12.880        56    11.0014  
...      ...       ...        ...  
6488  12.880        60    11.0014  
6489  12.880        60    11.0014  
6490  12.880        60    11.0014  
6491  13.635        56     8.9981  
6492  13.635        65     8.9981  

[6493 rows x 9 columns]

In [691]:

sub_df = pd.read_csv('./sampleSubmission.csv')
sub_df

datetime  count
0     2011-01-20 00:00:00      0
1     2011-01-20 01:00:00      0
2     2011-01-20 02:00:00      0
3     2011-01-20 03:00:00      0
4     2011-01-20 04:00:00      0
...                   ...    ...
6488  2012-12-31 19:00:00      0
6489  2012-12-31 20:00:00      0
6490  2012-12-31 21:00:00      0
6491  2012-12-31 22:00:00      0
6492  2012-12-31 23:00:00      0

[6493 rows x 2 columns]

In [692]:
show_df = pd.read_csv('./train.csv')
show_df

datetime  season  holiday  workingday  weather   temp  \
0      2011-01-01 00:00:00       1        0           0        1   9.84   
1      2011-01-01 01:00:00       1        0           0        1   9.02   
2      2011-01-01 02:00:00       1        0           0        1   9.02   
3      2011-01-01 03:00:00       1        0           0        1   9.84   
4      2011-01-01 04:00:00       1        0           0        1   9.84   
...                    ...     ...      ...         ...      ...    ...   
10881  2012-12-19 19:00:00       4        0           1        1  15.58   
10882  2012-12-19 20:00:00       4        0           1        1  14.76   
10883  2012-12-19 21:00:00       4        0           1        1  13.94   
10884  2012-12-19 22:00:00       4        0           1        1  13.94   
10885  2012-12-19 23:00:00       4        0           1        1  13.12   

        atemp  humidity  windspeed  casual  registered  count  
0      14.395        81     0.0000       3          13     16  
1      13.635        80     0.0000       8          32     40  
2      13.635        80     0.0000       5          27     32  
3      14.395        75     0.0000       3          10     13  
4      14.395        75     0.0000       0           1      1  
...       ...       ...        ...     ...         ...    ...  
10881  19.695        50    26.0027       7         329    336  
10882  17.425        57    15.0013      10         231    241  
10883  15.910        61    15.0013       4         164    168  
10884  17.425        61     6.0032      12         117    129  
10885  16.665        66     8.9981       4          84     88  

[10886 rows x 12 columns]

In [705]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


In [706]:
bike_df = pd.read_csv('./train.csv')
bike_df['datetime'] = pd.to_datetime(bike_df['datetime'])
bike_df

datetime  season  holiday  workingday  weather   temp  \
0     2011-01-01 00:00:00       1        0           0        1   9.84   
1     2011-01-01 01:00:00       1        0           0        1   9.02   
2     2011-01-01 02:00:00       1        0           0        1   9.02   
3     2011-01-01 03:00:00       1        0           0        1   9.84   
4     2011-01-01 04:00:00       1        0           0        1   9.84   
...                   ...     ...      ...         ...      ...    ...   
10881 2012-12-19 19:00:00       4        0           1        1  15.58   
10882 2012-12-19 20:00:00       4        0           1        1  14.76   
10883 2012-12-19 21:00:00       4        0           1        1  13.94   
10884 2012-12-19 22:00:00       4        0           1        1  13.94   
10885 2012-12-19 23:00:00       4        0           1        1  13.12   

        atemp  humidity  windspeed  casual  registered  count  
0      14.395        81     0.0000       3          13     16  
1      13.635        80     0.0000       8          32     40  
2      13.635        80     0.0000       5          27     32  
3      14.395        75     0.0000       3          10     13  
4      14.395        75     0.0000       0           1      1  
...       ...       ...        ...     ...         ...    ...  
10881  19.695        50    26.0027       7         329    336  
10882  17.425        57    15.0013      10         231    241  
10883  15.910        61    15.0013       4         164    168  
10884  17.425        61     6.0032      12         117    129  
10885  16.665        66     8.9981       4          84     88  

[10886 rows x 12 columns]

In [707]:
# 2. datetime 칼럼에서 시간 관련 특성 추출
bike_df['year'] = bike_df['datetime'].dt.year # year는 숫자형으로 두는 경우도 많습니다.
bike_df['month'] = bike_df['datetime'].dt.month
bike_df['dayofweek'] = bike_df['datetime'].dt.dayofweek
bike_df['hour'] = bike_df['datetime'].dt.hour

In [712]:
bike_df =bike_df.drop(['datetime'], axis=1)


KeyError: "['datetime'] not found in axis"

In [709]:
#X = bike_df.drop('count', axis=1).values
#y = bike_df['count']

X = bike_df.drop(['count', 'casual', 'registered'], axis=1)
y = bike_df['count']

In [713]:
categorical_features_to_encode = ['season', 'holiday', 'workingday', 'weather', 'month', 'dayofweek', 'hour']

In [714]:
X = pd.get_dummies(X, columns=categorical_features_to_encode, drop_first=True)

KeyError: "None of [Index(['season', 'holiday', 'workingday', 'weather', 'month', 'dayofweek',\n       'hour'],\n      dtype='object')] are in the [columns]"

In [715]:
# 중복 데이터 확인 및 제거
display(bike_df[bike_df.duplicated(keep=False)])
bike_df = bike_df.drop_duplicates()

season  holiday  workingday  weather  temp  atemp  humidity  windspeed  \
5020       4        0           0        1  9.84  12.88        65     7.0015   
5188       4        0           0        1  9.84  12.88        65     7.0015   

      casual  registered  count  year  month  dayofweek  hour  
5020       1          10     11  2011     12          5     6  
5188       1          10     11  2011     12          5     6

In [716]:
bike_df.head()

season  holiday  workingday  weather  temp   atemp  humidity  windspeed  \
0       1        0           0        1  9.84  14.395        81        0.0   
1       1        0           0        1  9.02  13.635        80        0.0   
2       1        0           0        1  9.02  13.635        80        0.0   
3       1        0           0        1  9.84  14.395        75        0.0   
4       1        0           0        1  9.84  14.395        75        0.0   

   casual  registered  count  year  month  dayofweek  hour  
0       3          13     16  2011      1          5     0  
1       8          32     40  2011      1          5     1  
2       5          27     32  2011      1          5     2  
3       3          10     13  2011      1          5     3  
4       0           1      1  2011      1          5     4

In [702]:
#X = bike_df.drop('count', axis =1).values
#y = bike_df['count'].values
X = bike_df.drop(['count'], axis=1).values
y = bike_df['count'].values  

In [717]:
bike_df.shape

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=156)
lr = LinearRegression()
lr.fit(X_train, y_train)

# 예측
y_pred = lr.predict(X_test)
print(y_pred[:3])


[-52.61062142 609.36944199  63.85181892]


In [704]:
X = bike_df.drop(['count', 'humidity', 'temp','windspeed'], axis=1).values
y = bike_df['count'].values  

In [718]:
mse = mean_squared_error(y_test, y_pred)
rmse= np.sqrt(mse)
mse, rmse

(np.float64(9960.55649521365), np.float64(99.80258761782507))

In [719]:
from sklearn.metrics import r2_score

r2_score(y_test, y_pred)

np.float64(0.6880593617510367)

In [ ]:

y = y.astype(int)

In [727]:

rf_clf = RandomForestRegressor(random_state=100, max_depth=3)
rf_clf.fit(X_train, y_train)
y_pred = rf_clf.predict(X_test)
y_pred[:3]

array([131.47836329, 648.78615112, 130.55214252])

In [728]:
from sklearn.model_selection import cross_val_score
neg_mse_scores = cross_val_score(lr, X, y, scoring='neg_mean_squared_error', cv=5)
neg_mse_scores

array([-9.73215968e+03, -7.10046079e+03, -2.08122310e+21, -1.63920618e+04,
       -1.72332481e+04])

In [729]:

RMSE=np.sqrt(neg_mse_scores*-1)
np.mean(RMSE), RMSE

(np.float64(9124084915.548918),
 array([9.86517090e+01, 8.42642320e+01, 4.56204241e+10, 1.28031488e+02,
        1.31275467e+02]))

In [730]:
r2_scores= cross_val_score(lr, X, y, scoring='r2', cv=5)
r2_scores, np.mean(r2_scores)

(array([ 1.79654071e-02,  6.84642465e-01, -1.25225599e+17,  6.48087895e-01,
         6.35994707e-01]),
 np.float64(-2.5045119706362184e+16))

In [731]:
mse = mean_squared_error(y_test, y_pred)
rmse= np.sqrt(mse)
mse, rmse

(np.float64(20549.410226474767), np.float64(143.35065478216262))

In [732]:
r2_score(y_test, y_pred)

np.float64(0.35644196739744327)

In [733]:
from sklearn.model_selection import cross_val_score

r2_scores = cross_val_score(lr, X, y, scoring='r2', cv=5)
r2_scores, np.mean(r2_scores)

(array([ 1.79654071e-02,  6.84642465e-01, -1.25225599e+17,  6.48087895e-01,
         6.35994707e-01]),
 np.float64(-2.5045119706362184e+16))

In [737]:
from sklearn.ensemble import GradientBoostingRegressor
gb_clf = GradientBoostingRegressor(random_state=0)
gb_clf.fit(X_train, y_train)
gb_pred = gb_clf.predict(X_test)
gb_pred[:3]


array([ 23.0271687 , 556.02491203, 101.87563556])

In [738]:
mse = mean_squared_error(y_test, gb_pred)
rmse= np.sqrt(mse)
mse, rmse

(np.float64(5914.590520090498), np.float64(76.90637502893046))

In [739]:
r2_score(y_test, gb_pred)

np.float64(0.8147692709031993)

In [740]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=156)

In [741]:
from xgboost import XGBRegressor
evals = [(X_test, y_test)]
xgb = XGBRegressor(n_estimators=400, learning_rate=0.1, max_depth=3, use_label_encoder=False)
xgb.fit(X_train, y_train, early_stopping_rounds=40, eval_set=evals, verbose=True)
xgb_pred = xgb.predict(X_test)


[0]	validation_0-rmse:242.79929
[1]	validation_0-rmse:227.62590
[2]	validation_0-rmse:214.54333
[3]	validation_0-rmse:203.13980
[4]	validation_0-rmse:192.83719
[5]	validation_0-rmse:183.06160
[6]	validation_0-rmse:175.08065
[7]	validation_0-rmse:167.67010
[8]	validation_0-rmse:161.57620
[9]	validation_0-rmse:155.92498
[10]	validation_0-rmse:151.31398
[11]	validation_0-rmse:146.73017
[12]	validation_0-rmse:143.07822
[13]	validation_0-rmse:139.68137
[14]	validation_0-rmse:136.58516
[15]	validation_0-rmse:133.87939
[16]	validation_0-rmse:131.54608
[17]	validation_0-rmse:129.29539
[18]	validation_0-rmse:127.37688
[19]	validation_0-rmse:125.15331
[20]	validation_0-rmse:123.32604
[21]	validation_0-rmse:121.39743
[22]	validation_0-rmse:119.94663
[23]	validation_0-rmse:118.45070
[24]	validation_0-rmse:116.82394
[25]	validation_0-rmse:115.64696
[26]	validation_0-rmse:114.18116
[27]	validation_0-rmse:113.03442
[28]	validation_0-rmse:112.10388
[29]	validation_0-rmse:110.71021
[30]	validation_0-rm

c:\Users\Admin\miniconda3\envs\hi_ml_env\lib\site-packages\xgboost\sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


[75]	validation_0-rmse:86.14645
[76]	validation_0-rmse:85.89119
[77]	validation_0-rmse:84.92212
[78]	validation_0-rmse:84.58875
[79]	validation_0-rmse:84.40289
[80]	validation_0-rmse:83.76984
[81]	validation_0-rmse:83.42311
[82]	validation_0-rmse:83.25565
[83]	validation_0-rmse:83.13575
[84]	validation_0-rmse:82.62246
[85]	validation_0-rmse:82.42569
[86]	validation_0-rmse:82.09690
[87]	validation_0-rmse:81.45403
[88]	validation_0-rmse:81.22285
[89]	validation_0-rmse:81.00536
[90]	validation_0-rmse:80.68441
[91]	validation_0-rmse:80.41108
[92]	validation_0-rmse:79.87544
[93]	validation_0-rmse:79.74355
[94]	validation_0-rmse:78.98485
[95]	validation_0-rmse:78.54718
[96]	validation_0-rmse:78.29725
[97]	validation_0-rmse:77.85276
[98]	validation_0-rmse:77.47534
[99]	validation_0-rmse:77.34564
[100]	validation_0-rmse:77.15174
[101]	validation_0-rmse:77.00748
[102]	validation_0-rmse:76.59607
[103]	validation_0-rmse:76.41685
[104]	validation_0-rmse:76.22670
[105]	validation_0-rmse:76.12413
[1

In [742]:
xgb_pred[:3]

array([-3.9030021e-01,  6.0153845e+02,  1.8178706e+02], dtype=float32)

In [743]:
mse = mean_squared_error(y_test, xgb_pred)
rmse= np.sqrt(mse)
mse, rmse

(np.float64(3049.6572010420155), np.float64(55.223701442786464))

In [744]:
r2_score(y_test, xgb_pred)

np.float64(0.9044920819242652)

In [745]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=156)

In [746]:
from lightgbm import LGBMRegressor

X = bike_df.drop('count', axis=1)
y = bike_df['count']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=156)

evals = [(X_test, y_test)]
lgb = LGBMRegressor(n_estimators=400, objective='regression', random_state=100)

#lgb.fit(X_train, y_train, early_stopping_rounds=40, eval_set=evals, eval_metric='multi_logloss', verbose=True) # verbose를 False로 변경

#lgb_pred = lgb.predict(X_test)

#print(f"R2 Score: {r2_score(y_test, lgb_pred)}")
#print(f"RMSE: {np.sqrt(mean_squared_error(y_test, lgb_pred))}")

In [330]:
# 다항 화귀

In [646]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures

In [507]:

X = bike_df.drop('count', axis =1).values
y = bike_df['count'].values

In [747]:
results = []

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=156)
model_poly = Pipeline([
  ('poly', PolynomialFeatures(degree=2, include_bias=False)),
  ('linear', LinearRegression())]
)
model_poly.fit(X_train, y_train)

Pipeline(steps=[('poly', PolynomialFeatures(include_bias=False)),
                ('linear', LinearRegression())])

In [748]:
pred_poly = model_poly.predict(X_test)
mean_squared_error(y_test, pred_poly)

np.float64(1.1727864419928869e-22)

In [749]:
r2_score(y_test, pred_poly)

np.float64(1.0)

In [750]:
for degree in range(1,5):
  model_poly = Pipeline([
    ('poly', PolynomialFeatures(degree=degree, include_bias=False)),
    ('linear', LinearRegression())]
  )
  model_poly.fit(X_train, y_train)
  pred_poly = model_poly.predict(X_test)
  mse = mean_squared_error(y_test, pred_poly)
  rmse = np.sqrt(mse)
  r2 = r2_score(y_test, pred_poly)
  
  results.append({ 'degree':degree,
                  'MSE':mse,
                  'RMSE':rmse,
                  'R2': r2})

pd.DataFrame(results)

degree           MSE          RMSE   R2
0       1  2.446953e-25  4.946669e-13  1.0
1       2  1.172786e-22  1.082953e-11  1.0
2       3  1.083747e-23  3.292031e-12  1.0
3       4  3.559962e-18  1.886786e-09  1.0

In [751]:
r2_score(y_test, pred_poly)

np.float64(1.0)

In [752]:
results = []
best_r2=-np.inf
best_model = None
best_pred = None

for degree in range(1,5):
  model_poly = Pipeline([
    ('poly', PolynomialFeatures(degree=degree, include_bias=False)),
    ('linear', LinearRegression())]
  )
  model_poly.fit(X_train, y_train)
  pred_poly = model_poly.predict(X_test)
  mse = mean_squared_error(y_test, pred_poly)
  rmse = np.sqrt(mse)
  r2 = r2_score(y_test, pred_poly)
  
  results.append({ 'degree':degree,
                  'MSE':mse,
                  'RMSE':rmse,
                  'R2': r2})
  if r2> best_r2:
    best_r2 = r2
    best_model = model_poly
    best_pred = pred_poly
    
pd.DataFrame(results)

degree           MSE          RMSE   R2
0       1  2.446953e-25  4.946669e-13  1.0
1       2  1.172786e-22  1.082953e-11  1.0
2       3  1.083747e-23  3.292031e-12  1.0
3       4  3.559962e-18  1.886786e-09  1.0

In [753]:
best_model.named_steps['poly'].degree

1

In [754]:
from sklearn.linear_model import Ridge, Lasso, ElasticNet

In [755]:
ridge = Ridge(alpha=1.0)
ridge.fit(X_train, y_train)
pred_ridge = ridge.predict(X_test)

mse = mean_squared_error(y_test, pred_ridge)
r2  = r2_score(y_test, pred_ridge)
mse, r2

(np.float64(1.5240085735986345e-11), np.float64(0.9999999999999996))

In [656]:
from sklearn.linear_model import RidgeCV, LassoCV
alphas = [0.001, 0.01, 0.1, 1, 10, 100]
ridge_cv = RidgeCV(alphas=alphas, cv=5)


In [657]:
ridge_cv.fit(X_train, y_train)
ridge_preds = ridge_cv.predict(X_test)

In [658]:
ridge_mse = mean_squared_error(y_test, ridge_preds)
ridge_r2 = r2_score(y_test, ridge_preds)
print(f'ridge cv mse: {ridge_mse:4f}, r2 : {ridge_r2:4f}')

ridge cv mse: 0.000000, r2 : 1.000000


In [375]:
lasso = Lasso(alpha=0.1)  # alpha 값 작으면 규제 약해짐
lasso.fit(X_train, y_train)
pred_lasso = lasso.predict(X_test)

print("\n[라쏘 회귀]")
print("MSE:", mean_squared_error(y_test, pred_lasso))
print("R2:", r2_score(y_test, pred_lasso))


[라쏘 회귀]
MSE: 4.1518598899911205e-06
R2: 0.9999999998735982


In [376]:
lasso_cv = LassoCV(alphas=alphas, cv=5, max_iter=10000)
lasso_cv.fit(X_train, y_train)
lasso_preds = lasso_cv.predict(X_test)
lasso_mse = mean_squared_error(y_test, lasso_preds)
lasso_r2 = r2_score(y_test, lasso_preds)

In [377]:
print(f"[개선 Lasso] 최적 alpha: {lasso_cv.alpha_}")
print(f"MSE: {lasso_mse:.3f}, R2: {lasso_r2:.3f}")

[개선 Lasso] 최적 alpha: 0.001
MSE: 0.000, R2: 1.000


In [ ]:
#LinearRegression, RandomForestRegressor 
# GradientBoostingRegressor, XGBRegressor, LGBMRegressor